[package]
name = "dump2dbs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-uring = "0.3.0"
futures = "0.3.21"
glob = "0.3.0"
anyhow = "1.0.58"
indicatif = "0.16.2"
tch = "0.8.0"